# Generated by Django 5.2.3 on 2025-07-02 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('rainfall_amount', models.FloatField()),
                ('collected_time', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flood_app.userprofile')),
            ],
        ),
    ]
