# Generated by Django 5.2.3 on 2025-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_app', '0002_rainfalldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodprediction',
            name='probability',
            field=models.FloatField(default=0.0),
        ),
    ]
