# Generated by Django 5.2.4 on 2025-08-01 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_app', '0004_cronjoblog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronjoblog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='floodalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='floodprediction',
            options={'ordering': ['predicted_date']},
        ),
        migrations.AlterModelOptions(
            name='rainfalldata',
            options={'ordering': ['-collected_time']},
        ),
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AlterField(
            model_name='floodalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='floodalert',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='floodprediction',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='floodprediction',
            name='predicted_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rainfalldata',
            name='collected_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rainfalldata',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rainfalldata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_reports', to='flood_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='recorded_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='flood_app_u_role_5379f3_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['location'], name='flood_app_u_locatio_e970cf_idx'),
        ),
    ]
